apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-server
          image: stevansehn/kube-express-server:2
